package org.bitbucket.cptshooter.shooterpack.admin;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JDialog;
import org.bitbucket.cptshooter.shooterpack.Main;

/**
 *
 * @author CptShooter
 */
public class Panel extends javax.swing.JDialog {

    DbConnect db;
    ArrayList<Admin> admin = new ArrayList<>();
    ArrayList<Link> link = new ArrayList<>();
    
    java.awt.Frame parent;
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    int locationX = (dim.width-this.getSize().width)/2;
    int locationY = (dim.height-this.getSize().height)/2;
        
    /**
     * Creates new form Admin
     */
    public Panel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        
        //visibility
        changeVisibility(false);
        
        String version = Main.VERSION+" build "+Main.BUILD;
        jButtonVersion.setToolTipText(version);
        
        db = new DbConnect();
        if(!db.connect()){
            jTextFieldStatus.setText("Database connect error!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonResetLink = new javax.swing.JButton();
        jButtonEditLink = new javax.swing.JButton();
        jScrollPaneLink = new javax.swing.JScrollPane();
        jListLink = new javax.swing.JList();
        jButtonAddAdmin = new javax.swing.JButton();
        jButtonEditAdmin = new javax.swing.JButton();
        jScrollPaneAdmin = new javax.swing.JScrollPane();
        jListAdmin = new javax.swing.JList();
        jTextFieldLogin = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldStatus = new javax.swing.JTextField();
        jButtonRefresh = new javax.swing.JButton();
        jButtonVersion = new javax.swing.JButton();
        backgroundAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Panel");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonResetLink.setText("Reset Link");
        jButtonResetLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetLinkActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonResetLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 240, -1));

        jButtonEditLink.setText("Edit Link");
        jButtonEditLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditLinkActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 240, -1));

        jListLink.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneLink.setViewportView(jListLink);

        getContentPane().add(jScrollPaneLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 240, 110));

        jButtonAddAdmin.setText("Add Admin");
        jButtonAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 240, -1));

        jButtonEditAdmin.setText("Edit Admin");
        jButtonEditAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 240, -1));

        jListAdmin.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneAdmin.setViewportView(jListAdmin);

        getContentPane().add(jScrollPaneAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 240, 110));
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 330, -1));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 330, -1));

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 330, -1));

        jTextFieldStatus.setEditable(false);
        jTextFieldStatus.setBackground(new Color(0,0,0,0));
        jTextFieldStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldStatus.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldStatus.setText("Login to Admin Panel");
        jTextFieldStatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldStatus.setFocusable(false);
        jTextFieldStatus.setOpaque(false);
        getContentPane().add(jTextFieldStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 330, -1));

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jButtonVersion.setText("Set Version to current");
        jButtonVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVersionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 160, -1));

        backgroundAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bitbucket/cptshooter/shooterpack/images/name.jpg"))); // NOI18N
        getContentPane().add(backgroundAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
       String login       = jTextFieldLogin.getText();
       char[] password    = jPasswordField.getPassword();
       if(db.login(login,password)){
           changeVisibility(true);
           getAdmin();
           getLink();
       }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAdminActionPerformed
        JDialog adminForm = new AdminForm(parent,true, db, null, true);
        adminForm.setLocation(locationX, locationY);
        adminForm.setVisible(true);
    }//GEN-LAST:event_jButtonAddAdminActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        getAdmin();
        getLink();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonEditAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditAdminActionPerformed
        String n = jListAdmin.getSelectedValue().toString();
        int index = n.indexOf("|");
        String name = n.substring(0, index).trim();
        boolean flag;
        if(name.equalsIgnoreCase(jTextFieldLogin.getText())){
            flag = true;
        }else{
            flag = false;
        }
        JDialog adminForm = new AdminForm(parent,true, db, name, flag);
        adminForm.setLocation(locationX, locationY);
        adminForm.setVisible(true);      
    }//GEN-LAST:event_jButtonEditAdminActionPerformed

    private void jButtonEditLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditLinkActionPerformed
        String k = jListLink.getSelectedValue().toString();
        int index = k.indexOf("|");
        String key = k.substring(0, index).trim();
        JDialog linkForm = new LinkForm(parent,true, db, key);
        linkForm.setLocation(locationX, locationY);
        linkForm.setVisible(true);
    }//GEN-LAST:event_jButtonEditLinkActionPerformed

    private void jButtonResetLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetLinkActionPerformed
        db.resetLink();
        getLink();
    }//GEN-LAST:event_jButtonResetLinkActionPerformed

    private void jButtonVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVersionActionPerformed
        db.saveInfo("Version",Main.VERSION);
        db.saveInfo("Build", Main.BUILD);
    }//GEN-LAST:event_jButtonVersionActionPerformed
        
    public static void setStatus(String text){
        jTextFieldStatus.setText(text);
    }
    
    private void changeVisibility(boolean flag){
        jTextFieldLogin.setVisible(!flag);
        jPasswordField.setVisible(!flag);
        jButtonLogin.setVisible(!flag);
        jButtonAddAdmin.setVisible(flag);
        jButtonEditAdmin.setVisible(flag);
        jButtonResetLink.setVisible(flag);
        jButtonEditLink.setVisible(flag);
        jScrollPaneAdmin.setVisible(flag);
        jScrollPaneLink.setVisible(flag);
        jButtonRefresh.setVisible(flag);
        jButtonVersion.setVisible(flag);
    }
    
    @SuppressWarnings("unchecked")
    private void getAdmin(){
        admin = db.getAdmin();
        int n = admin.size();
        String[] lines = new String[n];
        for(int i=0;i<n;i++){
            lines[i] = admin.get(i).toString();
        }
        jListAdmin.setListData(lines);
        admin.clear();
    }
    
    @SuppressWarnings("unchecked")
    private void getLink(){
        link = db.getLink();
        int n = link.size();
        String[] lines = new String[n];
        for(int i=0;i<n;i++){
            lines[i] = link.get(i).toString();
        }
        jListLink.setListData(lines);
        link.clear();
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Panel dialog = new Panel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundAdmin;
    private javax.swing.JButton jButtonAddAdmin;
    private javax.swing.JButton jButtonEditAdmin;
    private javax.swing.JButton jButtonEditLink;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonResetLink;
    private javax.swing.JButton jButtonVersion;
    private javax.swing.JList jListAdmin;
    private javax.swing.JList jListLink;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPaneAdmin;
    private javax.swing.JScrollPane jScrollPaneLink;
    private javax.swing.JTextField jTextFieldLogin;
    private static javax.swing.JTextField jTextFieldStatus;
    // End of variables declaration//GEN-END:variables
}
