package org.bitbucket.cptshooter.shooterpack;


import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.locks.LockSupport;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

/**
 *
 * @author CptShooter
 */
public class Main extends javax.swing.JFrame {

    Authentication authentication;

    public Main() {        
        initComponents();
        jProgressBar.setVisible(false);
        logoutButton.setVisible(false);
        playButton.setVisible(false);
        statusLabel.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jProgressBar = new javax.swing.JProgressBar();
        loginField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        titleText = new javax.swing.JLabel();
        loginText = new javax.swing.JLabel();
        passText = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        uncrafted = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextLog = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 750, 30));
        jPanel1.add(loginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 340, -1));
        jPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 340, -1));

        loginButton.setText("Login");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        titleText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleText.setForeground(new java.awt.Color(255, 255, 255));
        titleText.setText("ShooterPack");
        jPanel1.add(titleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        loginText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginText.setForeground(new java.awt.Color(255, 255, 255));
        loginText.setText("Login");
        jPanel1.add(loginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        passText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passText.setForeground(new java.awt.Color(255, 255, 255));
        passText.setText("Password");
        jPanel1.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        playButton.setText("Play");
        playButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        jPanel1.add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        statusLabel.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(51, 51, 51));
        statusLabel.setText("Status");
        statusLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        statusLabel.setOpaque(true);
        jPanel1.add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 340, -1));

        uncrafted.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        uncrafted.setForeground(new java.awt.Color(255, 255, 255));
        uncrafted.setText("Uncrafted.pl");
        jPanel1.add(uncrafted, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bitbucket/cptshooter/shooterpack/minecraft.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 270));

        jTabbedPane1.addTab("Main", jPanel1);

        jScrollPane1.setViewportView(jTextLog);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Log", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        login();
        //getPack();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        logout();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        Minecraft minecraft = new Minecraft(authentication.getUser());
        minecraft.run();
    }//GEN-LAST:event_playButtonActionPerformed

    public void login(){
       String login = loginField.getText();
       char[] password = passField.getPassword();
       authentication = new Authentication(login, password);
       if(authentication.connect()){
           loginText.setVisible(false);
           passText.setVisible(false);
           loginField.setVisible(false);
           passField.setVisible(false);
           loginButton.setVisible(false);
           playButton.setVisible(true);
           logoutButton.setVisible(true);
           statusLabel.setText("Login success!");
           statusLabel.setVisible(true);
           setTextLog("Login success!");  
       }else{
           if(authentication.getError()==1){
                statusLabel.setText(authentication.getErrorMessage());
                statusLabel.setVisible(true);
                setTextLog(authentication.getErrorMessage());  
           }
       }
    }
    
    public void logout(){
        //authentication.disconnect();
        loginText.setVisible(true);
        passText.setVisible(true);
        loginField.setVisible(true);
        passField.setVisible(true);
        loginButton.setVisible(true);
        playButton.setVisible(false);
        logoutButton.setVisible(false);
        statusLabel.setText("Logout success!");
        statusLabel.setVisible(true);
        setTextLog("Logout success!");  
    }
    
    public void getPack(){
        String packUrl = "http://cptshooter.esy.es/tapety.zip";
        jProgressBar.setMinimum(0);
        jProgressBar.setMaximum(100);
        jProgressBar.setStringPainted(true);
        jProgressBar.setVisible(true);
        try {
            final Download download = new Download(new URL(packUrl));
            download.start();
            final AtomicBoolean running = new AtomicBoolean(false);
            running.set(!running.get());
            if (running.get()) {
                new Thread() {
                    @Override
                    public void run() {
                        //download file in a thread
                        while (running.get()) {
                            LockSupport.parkNanos(TimeUnit.MILLISECONDS.toNanos(200)); 
                            jProgressBar.setValue(download.getProgress());
                            jProgressBar.setBorder(BorderFactory.createTitledBorder(download.getStatusS()));                            
                            if(download.getStatus()==5){
                                setTextLog(download.getStatusS());                                
                            }else{
                                setTextLog(download.getStatusS() + " at: " + download.getProgress() + "%");
                            }                          
                        }
                    }
                }.start();
            }            
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setTextLog(String log){
        Calendar cal = Calendar.getInstance();
    	cal.getTime();
    	SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String text = jTextLog.getText();
        jTextLog.setText(text + "\n" + sdf.format(cal.getTime()) + " | " + log);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextLog;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginText;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passText;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleText;
    private javax.swing.JLabel uncrafted;
    // End of variables declaration//GEN-END:variables
}
